title: Nicheknights Wiki
description: A wiki of niches in arknights 
theme: just-the-docs

url: https://nicheknights.stressd.xyz

aux_links:
  Arknights Wiki: https://arknights.wiki.gg/
  Contact: /contact

ruby sass: 
  quiet_deps: true

callouts: 
  note: 
    title: Note
    color: purple
