title: Nicheknights Wiki
description: A wiki of niches in arknights 
theme: just-the-docs

url: https://nicheknights.stressd.xyz

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

ruby sass: 
  quiet_deps: true
